language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zakidr789/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zakidr789/docker-react npm run test -- --coverage 
deploy:
  provider: eleasticbeanstalk
  region: "eu-north"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-211125648928"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
